import { albums } from "./albums";
import { randomItem } from "../../utils/random";
import { images } from "./images";

const demoAudio =
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3";

const titles = [
  "Island Vibes",
  "Late Night Text",
  "Soft Whispers",
  "Palm Trees",
  "Street Melody",
  "Heaven Knows",
  "Sunset Feelings",
  "Slow Wine",
  "Blessed Path",
  "City Rhythm",
  "Moonlight Dance",
  "Golden Love",
  "Hustle Hard",
  "Sacred Heart",
  "Cool Breeze",
  "Vibe With Me",
  "Deep Confessions",
  "No Pressure",
  "Faith Over Fear",
  "Night Cruiser",
  "Sweet Talk",
  "Higher Calling",
  "Peace of Mind",
  "Dark Mode",
  "Glow Up",
  "Holy Ground",
  "Energy Flow",
  "True Colors",
  "Street Dreams",
  "Praise Song",
  "Good Company",
  "Low Key",
  "Big Moves",
  "Miracle Light",
  "Smooth Operator",
  "Forever Yours",
  "Trap Nights",
  "Grace Wins",
  "Side by Side",
  "Weekend Mood",
  "Prayer Hands",
  "Chill Zone",
  "Wave Rider",
  "King's Anthem",
  "Gentle Touch",
  "Sound of Joy",
  "Midnight Vibes",
  "Pure Intentions",
  "Stay Blessed",
  "Slow Groove",
  "Dream Chaser",
  "Spirit Rise",
  "Lost Without You",
  "Sunshine Smile",
  "No Limits",
  "Divine Timing",
  "Rhythm & Soul",
  "Ocean Waves",
  "Sacred Fire",
  "Cloud Nine",
  "Big Energy",
  "Heart & Mind",
  "Victory Lap",
  "Morning Glory",
  "All In",
  "Soul Therapy",
  "Grateful",
  "Lights & Love",
  "Freedom Call",
  "Summer Bounce",
  "True Story",
  "Living Proof",
  "Golden Child",
  "Calm Spirit",
  "On the Low",
  "Shine Bright",
  "Higher Love",
  "Dance With Me",
  "Good Vibes Only",
  "Sacred Dreams",
  "Late Night Drive",
  "Faithful One",
  "Smooth Sailing",
  "Pure Gold",
  "Blessings Flow",
  "Heart on Fire",
  "No Stress",
  "Spirit Flow",
  "Wild Energy",
  "Closer",
  "Joyful Noise",
  "Midnight Prayer",
  "Fresh Start",
  "Open Heaven",
  "Drip Season",
  "Peaceful Mind",
  "Soul Glow",
  "Rise & Shine",
];

export const songs = Array.from({ length: 60 }, (_, i) => {
  const album = randomItem(albums);

  return {
    id: `song-${i + 1}`,
    title: titles[Math.floor(Math.random() * 100)],
    albumId: album.id,
    artistId: album.artistId,
    duration: `${2 + Math.floor(Math.random() * 3)}:${
      10 + Math.floor(Math.random() * 49)
    }`,
    audio: demoAudio,
    plays: Math.floor(Math.random() * 1_000_000),
    image: randomItem(images),
  };
});
